name: Build and Deploy Dev

on:
  push:
    branches: [ "develop" ]

env:
  PROJECT_ID: vaulted-art-327315 
  GAR_LOCATION: europe-west3
  REGION: us-central1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4.1.1
        with:
          ref: develop

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2.1.2'
        with:
          project_id: '${{env.PROJECT_ID}}'
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.SA_EMAIL }}'

      - name: Get latest commit SHA
        run: echo "DEVELOP_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
      - name: Authenticate Docker to Google Cloud Artifact Registry
        id: docker-auth
        uses: 'docker/login-action@v3.1.0'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Container
        run: |
          docker build --platform linux/amd64 --build-arg profile=dev -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/stadtmeldeappregistry/backend-image-dev:${{ github.sha }}" ./stadtmeldeapp
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/stadtmeldeappregistry/backend-image-dev:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy-backend-dev
        uses: google-github-actions/deploy-cloudrun@v2.2.0
        with:
          service: backendservice-dev
          region: ${{ env.REGION }}
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/stadtmeldeappregistry/backend-image-dev:${{ env.DEVELOP_SHA }}"
